# Hello, Majrusz over there!
# Since one of 1.19.2 release, configs used by my mods are mostly server-side
# which means that they are now stored separately per world. Thanks to this change,
# configuration files are synchronised with other players on the server.
#  
# Anyway, here are the exact locations:
#   Singleplayer: %appdata%/saves/<world>/serverconfig
#   Multiplayer: <your server>/<world>/serverconfig
#  
# If you have any questions or want to see some more configs, feel
# free to contact me on my Discord server! Hope to see you there :D
discord_url = "https://discord.gg/9UF774WcuW"

